// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/get_images.ts";
import * as $1 from "./routes/api/get_temp_post_url.ts";
import * as $2 from "./routes/api/image_updated.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Images.tsx";
import * as $$1 from "./islands/Uploader.tsx";

const manifest = {
  routes: {
    "./routes/api/get_images.ts": $0,
    "./routes/api/get_temp_post_url.ts": $1,
    "./routes/api/image_updated.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Images.tsx": $$0,
    "./islands/Uploader.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
